version: '3.3'

services:
  backend-api:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
  backend-db:
    image: mysql:8
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USER=wolly
      - MYSQL_PASSWORD=wolly
      - MYSQL_ROOT_PASSWORD=wolly
      - MYSQL_DATABASE=wollyapi
    volumes:
      - my-db:/var/lib/mysql
networks:
  default:
volumes:
  my-db: