version: '3.3'

services:
  backend-api:
    depends_on:
      - database
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile 
    ports:
      - "8080:8080"
    
     
  database:
    image: postgres:14.1-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=wolly
    ports:
      - '5432:5432' 
    volumes:
      - my-db:/var/lib/postgresql/data

volumes:
  my-db:
   driver: local 
      