version: '3.3'

services:
  backend-api:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
networks:
  default:
volumes:
  wolly-volume: