name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    -
      name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: omegadevs
        password: ${{ secrets.DOCKER_HUB_API_KEY }}
       
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag omegadevs/wolly-api:latest
    
    - name: Push the latest Docker image
      run: docker push omegadevs/wolly-api:latest
